---
- hosts: ocr-grp
  
  become: true

  vars_files:
    - ../vars/servers.yml

  tasks:
    - name: Copying the Directory's contents (sub directories/files)
      become: true 
      copy:
        src: ../grafana/
        dest: "{{ grafana_path }}"
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"        
        mode: 0755