---
- hosts: capture-detection-grp
  vars_files:
    - ../vars/servers.yml
  tasks:
    - name: Copying the Capture Detection models
      become: true 
      copy:
        src: "../models/{{ capture_detection_name }}/"
        dest: "{{ model_path }}"
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"        
        mode: 0755

- hosts: filter-grp  
  vars_files:
    - ../vars/servers.yml
  tasks:
    - name: Copying the Filter models
      become: true 
      copy:
        src: "../models/{{ filter_name }}/"
        dest: "{{ model_path }}"
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"        
        mode: 0755

- hosts: ocr-grp  
  vars_files:
    - ../vars/servers.yml
  tasks:
    - name: Copying the OCR models        
      become: true 
      copy:
        src: "../models/{{ ocr_name }}/"
        dest: "{{ model_path }}"
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"        
        mode: 0755