{
 "title": "EVA Performance Evaluation",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Detection time in ms [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(detection_time_seconds_per_frame_sum[1m])/rate(detection_time_seconds_per_frame_count[1m]) * 1000",
     "legendFormat": "{{instance}} | {{job}}"
    }
   ]
  },
  {
   "title": "Captured Bytes [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(bytes_per_captured_frame_sum[1m])/rate(bytes_per_captured_frame_count[1m])",
     "legendFormat": "{{instance}} | {{job}}"
    }
   ]
  },
  {
   "title": "Sent Bytes [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(bytes_per_sent_frame_sum[1m])/rate(bytes_per_sent_frame_count[1m]) ",
     "legendFormat": "{{instance}} | {{job}}"
    }
   ]
  },
  {
   "title": "FPS In [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(captured_frames_total[1m])",
     "legendFormat": "{{instance}} | {{job}}"
    }
   ]
  },
  {
   "title": "FPS out [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    { "expr": "rate(sent_frames_total[1m])", "legendFormat": "{{instance}} | {{job}}" }
   ]
  }
 ]
}